#HTML

follow_the_rhythm_bienvenue:
    path:     /
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:index }
    
follow_the_rhythm_accueil:
    path:     /accueil/{page}/{sens}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:index }

follow_the_rhythm_artiste:
    path:   /artiste
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:artiste }
    
follow_the_rhythm_concert:
    path:   /concert
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:concert }

follow_the_rhythm_contacts:
    path:   /contacts
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:contacts }
  
follow_the_rhythm_credits:
    path:   /credits
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:credits }
    
follow_the_rhythm_soumettreActualite:
    path:   /soumettreActualite
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:soumettreActualite }
    
follow_the_rhythm_soumettreTopicPromotions:
    path:   /soumettreTopicPromotions
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:soumettreTopicPromotions }
    
follow_the_rhythm_soumettreTopicNews:
    path:   /soumettreTopicNews
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:soumettreTopicNews }
    
follow_the_rhythm_soumettreTopicEspacePrive:
    path:   /soumettreTopicEspacePrive
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:soumettreTopicEspacePrive }
    
follow_the_rhythm_soumettreTopicConcerts:
    path:   /soumettreTopicConcerts
    defaults: {_controller: follow_the_rhythmSymfonyBundle:Symfony:soumettreTopicConcerts }

follow_the_rhythm_pageArtiste:
    path:   /pageArtiste/{id}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:pageArtiste }
    
follow_the_rhythm_pageUtilisateur:
    path:   /pageUtilisateur/{id}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:pageUtilisateur }
    
follow_the_rhythm_pageConcert:
    path:   /pageConcert/{id}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:pageConcert }
    
follow_the_rhythm_accueilForum:
    path:   /accueilForum
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:accueilForum }
        
follow_the_rhythm_accueilArtistesUniquement:
    path:   /accueilArtistesUniquement/{page}/{sens}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:accueilArtistesUniquement }
    
follow_the_rhythm_modifierSupprimerActualite:
    path:   /modifierSupprimerActualite
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:modifierSupprimerActualite }
    
follow_the_rhythm_modifierActualite:
    path:     /modifierActualite/{id}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:modifierActualite }
    
follow_the_rhythm_aide:
    path:     /aide
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:aide }

#-----------------------------------------------------------------------------------------------------------------------------------
#Forum 

follow_the_rhythm_categorieNews:
    path:     /forum/news
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:categorieNews }

follow_the_rhythm_categorieEspacePrive:
    path:     /forum/espacePrive
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:categorieEspacePrive }

follow_the_rhythm_categorieConcert:
    path:     /forum/concert
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:categorieConcert }

follow_the_rhythm_categoriePromotions:
    path:     /forum/promotion
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:categoriePromotion }
    
follow_the_rhythm_messages:
    path:     /forum/topic/{topicId}
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:messages }
    

#-----------------------------------------------------------------------------------------------------------------------------------
#JSON 

follow_the_rhythm_news:
    path:     /API/news
    defaults: { _controller: follow_the_rhythmSymfonyBundle:Symfony:news }
